### PR TITLE
Console application Improvements

### PR DESCRIPTION
**Pull request by wrhyme29**
It now loads mods in interactive mode as well.

The only thing it doesn't currently handle well are the promos for other mods (like your Noisy Cricket example).

Let me know if you have any questions

### CODE REVIEW

**Comment by MigrantP** [comment]
The diff in 0315a42 is huge, can you point out the actual changes?

**Comment by wrhyme29** [comment]
_LoadModAssemblies_ adds in the NamespaceList which is used for loading mods.
_LoadAllModEnvironments_ and _LoadAllModHeroesOrVillains_ are new functions that pull the mods from the assembly.
_HandleGetHeroesInTheBoxRequest_ is updated to use the new mod loading functions
_ConfigureGameInteractively_ is the big changes. Essentially, every step along the way branches to include mods as well. 

There may be a few other small changes to facilitate those changes, such as the GameMod enum.

**Comment by wrhyme29** [comment]
If you would prefer, I can try to make more targetted changes as opposed to pasting the new version in. I can close this PR and open a new one with that

**Comment by MigrantP** [comment]
If it's not too much trouble, it would be easier to check the diff with few changes. I think maybe it's because of whitespace/etc changes, but it's 9868 lines.

**Comment by wrhyme29** [comment]
Closing, #5 has been created that is hopefully easier to review

**Pull request closed without merging**
